package com.springmvc.pojo;
/**
 * Description：评论图片表
 * @author boyang
 * @date 2019/5/6 11:34
 * @param
 * @return
 */

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Date;

public class ArticleImg {
    /**
     主键id
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     *
     文章图片
     */
    private String img;

    /**
     添加时间
     */
    private Date addtime;
    /**
     文章id
     */
    private Integer articleid;

    /**

     */
    public Integer getId() {
        return id;
    }

    /**

     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_img.img
     *
     * @return the value of article_img.img
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_img.img
     *
     * @param img the value for article_img.img
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_img.addTime
     *
     * @return the value of article_img.addTime
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_img.addTime
     *
     * @param addtime the value for article_img.addTime
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_img.articleId
     *
     * @return the value of article_img.articleId
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_img.articleId
     *
     * @param articleid the value for article_img.articleId
     *
     * @mbg.generated Mon May 06 11:34:19 CST 2019
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }
}