package com.springmvc.pojo;

import java.util.Date;

public class ArticleClick {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_click.id
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_click.adminId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_click.articleId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    private Integer articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_click.clickStatus
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    private Integer clickstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_click.modifiTime
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    private Date modifitime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.id
     *
     * @return the value of article_click.id
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.id
     *
     * @param id the value for article_click.id
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.adminId
     *
     * @return the value of article_click.adminId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.adminId
     *
     * @param adminid the value for article_click.adminId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.articleId
     *
     * @return the value of article_click.articleId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.articleId
     *
     * @param articleid the value for article_click.articleId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.clickStatus
     *
     * @return the value of article_click.clickStatus
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Integer getClickstatus() {
        return clickstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.clickStatus
     *
     * @param clickstatus the value for article_click.clickStatus
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setClickstatus(Integer clickstatus) {
        this.clickstatus = clickstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.modifiTime
     *
     * @return the value of article_click.modifiTime
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Date getModifitime() {
        return modifitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.modifiTime
     *
     * @param modifitime the value for article_click.modifiTime
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setModifitime(Date modifitime) {
        this.modifitime = modifitime;
    }
}