package com.springmvc.pojo;
/**
 * Description：文章点击表
 * @author boyang
 * @date 2019/5/6 11:28
 * @param
 * @return
 */
import org.springframework.stereotype.Repository;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Date;
@Repository
public class ArticleClick {
    /**
     主键id
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;
    /**
     用户id
     */
    private Integer adminid;

    /**
     文章id
     */
    private Integer articleid;

    /**
     点赞状态（1点赞，0未点赞）默认为0     */
    private Integer clickstatus;

    /**
     *
     最终修改时间
     */
    private Date modifitime;

    @Override
    public String toString() {
        return "ArticleClick{" +
                "id=" + id +
                ", adminid=" + adminid +
                ", articleid=" + articleid +
                ", clickstatus=" + clickstatus +
                ", modifitime=" + modifitime +
                '}';
    }

    public Integer getId() {
        return id;
    }

    /**
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**

     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.articleId
     *
     * @param articleid the value for article_click.articleId
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.clickStatus
     *
     * @return the value of article_click.clickStatus
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Integer getClickstatus() {
        return clickstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.clickStatus
     *
     * @param clickstatus the value for article_click.clickStatus
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setClickstatus(Integer clickstatus) {
        this.clickstatus = clickstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_click.modifiTime
     *
     * @return the value of article_click.modifiTime
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public Date getModifitime() {
        return modifitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_click.modifiTime
     *
     * @param modifitime the value for article_click.modifiTime
     *
     * @mbg.generated Thu Apr 25 14:07:08 CST 2019
     */
    public void setModifitime(Date modifitime) {
        this.modifitime = modifitime;
    }
}