package com.springmvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Repository;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Date;
@Repository
public class BankCard {
    /**
     * 自增id
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     * 银行卡名称
     */
    private String title;

    /**
     * 银行卡类别id
     */
    private Integer cardcategoryid;
    /**
     * 标签id
     */
    private Integer tagid;
    /**
     * 银行卡图片
     */
    private String img;
    /**
     * 审核方式
     */
    private String reviewway;

    /**
     * 到账方式
     */
    private String accountway;

    /**
     * 简介
     */
    private String info;

    /**
     * 网址链接
     */
    private String url;

    /**
     * 上架状态
     */
    private Byte status;

    /**
     * 添加时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @Column(name = "add_time")
    private Date addTime;

    /**
     * 有无连接状态码
     */
    private Integer statuscode;
    /**
     *流量
     */
    private Integer pv;

    /**
     * 独立访客
     */
    private Integer uv;

    /**
     * uv收益
     */
    private String uvEarnings;

    /**
     * 关联用户表
     */
    private Integer adminid;

    /**
     * 点击量
     */
    private Integer click;

    /**
     * 审核失败原因
     */
    private String auditfailed;

    /**
     * 生成的短链接
     */
    private String shorturl;

    /**
     * 卡福利
     */
    private String welfare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.id
     *
     * @return the value of bank_card.id
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.id
     *
     * @param id the value for bank_card.id
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.title
     *
     * @return the value of bank_card.title
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.title
     *
     * @param title the value for bank_card.title
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.cardCategoryId
     *
     * @return the value of bank_card.cardCategoryId
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getCardcategoryid() {
        return cardcategoryid;
    }

    public void setCardcategoryid(Integer cardcategoryid) {
        this.cardcategoryid = cardcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.tagId
     *
     * @return the value of bank_card.tagId
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.tagId
     *
     * @param tagid the value for bank_card.tagId
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.img
     *
     * @return the value of bank_card.img
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.img
     *
     * @param img the value for bank_card.img
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.reviewWay
     *
     * @return the value of bank_card.reviewWay
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getReviewway() {
        return reviewway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.reviewWay
     *
     * @param reviewway the value for bank_card.reviewWay
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setReviewway(String reviewway) {
        this.reviewway = reviewway == null ? null : reviewway.trim();
    }

    @Override
    public String toString() {
        return "BankCard{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", cardcategoryid='" + cardcategoryid + '\'' +
                ", tagid=" + tagid +
                ", img='" + img + '\'' +
                ", reviewway='" + reviewway + '\'' +
                ", accountway='" + accountway + '\'' +
                ", info='" + info + '\'' +
                ", url='" + url + '\'' +
                ", status=" + status +
                ", addTime=" + addTime +
                ", statuscode=" + statuscode +
                ", pv=" + pv +
                ", uv=" + uv +
                ", uvEarnings='" + uvEarnings + '\'' +
                ", adminid=" + adminid +
                ", click=" + click +
                ", auditfailed='" + auditfailed + '\'' +
                ", shorturl='" + shorturl + '\'' +
                ", welfare='" + welfare + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.accountWay
     *
     * @return the value of bank_card.accountWay
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getAccountway() {
        return accountway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.accountWay
     *
     * @param accountway the value for bank_card.accountWay
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setAccountway(String accountway) {
        this.accountway = accountway == null ? null : accountway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.info
     *
     * @return the value of bank_card.info
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.info
     *
     * @param info the value for bank_card.info
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.url
     *
     * @return the value of bank_card.url
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.url
     *
     * @param url the value for bank_card.url
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.status
     *
     * @return the value of bank_card.status
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.status
     *
     * @param status the value for bank_card.status
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.add_time
     *
     * @return the value of bank_card.add_time
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.add_time
     *
     * @param addTime the value for bank_card.add_time
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.statusCode
     *
     * @return the value of bank_card.statusCode
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getStatuscode() {
        return statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.statusCode
     *
     * @param statuscode the value for bank_card.statusCode
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setStatuscode(Integer statuscode) {
        this.statuscode = statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.pv
     *
     * @return the value of bank_card.pv
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.pv
     *
     * @param pv the value for bank_card.pv
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.uv
     *
     * @return the value of bank_card.uv
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.uv
     *
     * @param uv the value for bank_card.uv
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.uv_earnings
     *
     * @return the value of bank_card.uv_earnings
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getUvEarnings() {
        return uvEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.uv_earnings
     *
     * @param uvEarnings the value for bank_card.uv_earnings
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setUvEarnings(String uvEarnings) {
        this.uvEarnings = uvEarnings == null ? null : uvEarnings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.adminId
     *
     * @return the value of bank_card.adminId
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.adminId
     *
     * @param adminid the value for bank_card.adminId
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.click
     *
     * @return the value of bank_card.click
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.click
     *
     * @param click the value for bank_card.click
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.auditFailed
     *
     * @return the value of bank_card.auditFailed
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getAuditfailed() {
        return auditfailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.auditFailed
     *
     * @param auditfailed the value for bank_card.auditFailed
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setAuditfailed(String auditfailed) {
        this.auditfailed = auditfailed == null ? null : auditfailed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.shortUrl
     *
     * @return the value of bank_card.shortUrl
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getShorturl() {
        return shorturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.shortUrl
     *
     * @param shorturl the value for bank_card.shortUrl
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setShorturl(String shorturl) {
        this.shorturl = shorturl == null ? null : shorturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.welfare
     *
     * @return the value of bank_card.welfare
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public String getWelfare() {
        return welfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.welfare
     *
     * @param welfare the value for bank_card.welfare
     *
     * @mbg.generated Tue Apr 23 10:30:19 CST 2019
     */
    public void setWelfare(String welfare) {
        this.welfare = welfare == null ? null : welfare.trim();
    }
}