package com.springmvc.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Date;

/**
 * Description：推广登录类  推广用户信息表
 * @param
 * @author boyang
 * @date 2019/5/7 16:53
 * @return
 */
public class FriendAdmin {
    /**
     自增id
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     推广表id
     */
    private Integer friendid;

    /**
     账号
     */
    private String account;

    /**
     密码
     */
    private String pwd;

    /**
     对应的短连接
     */
    private String shorturl;

    /**
     当天扣量
     */
    private Integer intradayquantity;

    /**
     默认扣量
     */
    private Integer defaultquantity;

    /**
     添加时间
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.id
     *
     * @return the value of friend_admin.id
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.id
     *
     * @param id the value for friend_admin.id
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.friendId
     *
     * @return the value of friend_admin.friendId
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public Integer getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.friendId
     *
     * @param friendid the value for friend_admin.friendId
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setFriendid(Integer friendid) {
        this.friendid = friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.account
     *
     * @return the value of friend_admin.account
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.account
     *
     * @param account the value for friend_admin.account
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.pwd
     *
     * @return the value of friend_admin.pwd
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.pwd
     *
     * @param pwd the value for friend_admin.pwd
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.shortUrl
     *
     * @return the value of friend_admin.shortUrl
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public String getShorturl() {
        return shorturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.shortUrl
     *
     * @param shorturl the value for friend_admin.shortUrl
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setShorturl(String shorturl) {
        this.shorturl = shorturl == null ? null : shorturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.intradayQuantity
     *
     * @return the value of friend_admin.intradayQuantity
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public Integer getIntradayquantity() {
        return intradayquantity;
    }

    @Override
    public String toString() {
        return "FriendAdmin{" +
                "id=" + id +
                ", friendid=" + friendid +
                ", account='" + account + '\'' +
                ", pwd='" + pwd + '\'' +
                ", shorturl='" + shorturl + '\'' +
                ", intradayquantity=" + intradayquantity +
                ", defaultquantity=" + defaultquantity +
                ", addtime=" + addtime +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.intradayQuantity
     *
     * @param intradayquantity the value for friend_admin.intradayQuantity
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setIntradayquantity(Integer intradayquantity) {
        this.intradayquantity = intradayquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.defaultQuantity
     *
     * @return the value of friend_admin.defaultQuantity
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public Integer getDefaultquantity() {
        return defaultquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.defaultQuantity
     *
     * @param defaultquantity the value for friend_admin.defaultQuantity
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setDefaultquantity(Integer defaultquantity) {
        this.defaultquantity = defaultquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_admin.addTime
     *
     * @return the value of friend_admin.addTime
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_admin.addTime
     *
     * @param addtime the value for friend_admin.addTime
     * @mbg.generated Tue May 07 16:53:06 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}