package com.springmvc.pojo;

import org.springframework.stereotype.Repository;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Repository
public class Goodsuvdata {
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    @Column(name = "goodsId")
    private Integer goodsid;


    private Integer uone;


    private Integer utwo;


    private Integer uthree;


    private Integer ufour;

    private Integer ufive;


    private Integer usat;


    private Integer usunday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.id
     *
     * @return the value of goodsuvdata.id
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.id
     *
     * @param id the value for goodsuvdata.id
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.goodsId
     *
     * @return the value of goodsuvdata.goodsId
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.goodsId
     *
     * @param goodsid the value for goodsuvdata.goodsId
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.uone
     *
     * @return the value of goodsuvdata.uone
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUone() {
        return uone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.uone
     *
     * @param uone the value for goodsuvdata.uone
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUone(Integer uone) {
        this.uone = uone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.utwo
     *
     * @return the value of goodsuvdata.utwo
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUtwo() {
        return utwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.utwo
     *
     * @param utwo the value for goodsuvdata.utwo
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUtwo(Integer utwo) {
        this.utwo = utwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.uthree
     *
     * @return the value of goodsuvdata.uthree
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUthree() {
        return uthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.uthree
     *
     * @param uthree the value for goodsuvdata.uthree
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUthree(Integer uthree) {
        this.uthree = uthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.ufour
     *
     * @return the value of goodsuvdata.ufour
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUfour() {
        return ufour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.ufour
     *
     * @param ufour the value for goodsuvdata.ufour
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUfour(Integer ufour) {
        this.ufour = ufour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.ufive
     *
     * @return the value of goodsuvdata.ufive
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUfive() {
        return ufive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.ufive
     *
     * @param ufive the value for goodsuvdata.ufive
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUfive(Integer ufive) {
        this.ufive = ufive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.usat
     *
     * @return the value of goodsuvdata.usat
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUsat() {
        return usat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.usat
     *
     * @param usat the value for goodsuvdata.usat
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUsat(Integer usat) {
        this.usat = usat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsuvdata.usunday
     *
     * @return the value of goodsuvdata.usunday
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getUsunday() {
        return usunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsuvdata.usunday
     *
     * @param usunday the value for goodsuvdata.usunday
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setUsunday(Integer usunday) {
        this.usunday = usunday;
    }
}