package com.springmvc.pojo;

import org.springframework.stereotype.Repository;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Repository
public class Goodspvdata {
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    @Column(name = "goodId")
    private Integer goodid;


    private Integer pone;


    private Integer ptwo;

    private Integer pthree;


    private Integer pfour;

    private Integer pfive;


    private Integer psat;


    private Integer psunday;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.goodId
     *
     * @return the value of goodspvdata.goodId
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.goodId
     *
     * @param goodid the value for goodspvdata.goodId
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.pone
     *
     * @return the value of goodspvdata.pone
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPone() {
        return pone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.pone
     *
     * @param pone the value for goodspvdata.pone
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPone(Integer pone) {
        this.pone = pone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.ptwo
     *
     * @return the value of goodspvdata.ptwo
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPtwo() {
        return ptwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.ptwo
     *
     * @param ptwo the value for goodspvdata.ptwo
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPtwo(Integer ptwo) {
        this.ptwo = ptwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.pthree
     *
     * @return the value of goodspvdata.pthree
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPthree() {
        return pthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.pthree
     *
     * @param pthree the value for goodspvdata.pthree
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPthree(Integer pthree) {
        this.pthree = pthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.pfour
     *
     * @return the value of goodspvdata.pfour
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPfour() {
        return pfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.pfour
     *
     * @param pfour the value for goodspvdata.pfour
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPfour(Integer pfour) {
        this.pfour = pfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.pfive
     *
     * @return the value of goodspvdata.pfive
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPfive() {
        return pfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.pfive
     *
     * @param pfive the value for goodspvdata.pfive
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPfive(Integer pfive) {
        this.pfive = pfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.psat
     *
     * @return the value of goodspvdata.psat
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPsat() {
        return psat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.psat
     *
     * @param psat the value for goodspvdata.psat
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPsat(Integer psat) {
        this.psat = psat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodspvdata.psunday
     *
     * @return the value of goodspvdata.psunday
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public Integer getPsunday() {
        return psunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodspvdata.psunday
     *
     * @param psunday the value for goodspvdata.psunday
     *
     * @mbg.generated Fri Mar 22 15:11:15 CST 2019
     */
    public void setPsunday(Integer psunday) {
        this.psunday = psunday;
    }
}