package com.springmvc.pojo;

public class LoanTerm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_term.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_term.term
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    private String term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_term.id
     *
     * @return the value of loan_term.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    private  Integer indexLoan;

    public Integer getIndexLoan() {
        return indexLoan;
    }

    public void setIndexLoan(Integer indexLoan) {
        this.indexLoan = indexLoan;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_term.id
     *
     * @param id the value for loan_term.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_term.term
     *
     * @return the value of loan_term.term
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_term.term
     *
     * @param term the value for loan_term.term
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }
}