package com.springmvc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Column;
import java.util.Date;

public class MoneyInfo {

    private Integer indexMoney;

    public Integer getIndexMoney() {
        return indexMoney;
    }

    public void setIndexMoney(Integer indexMoney) {
        this.indexMoney = indexMoney;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_info.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_info.moneyName
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    private String moneyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_info.addTime
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @Column(name="addTime")
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_info.id
     *
     * @return the value of money_info.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_info.id
     *
     * @param id the value for money_info.id
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_info.moneyName
     *
     * @return the value of money_info.moneyName
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public String getMoneyname() {
        return moneyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_info.moneyName
     *
     * @param moneyname the value for money_info.moneyName
     *
     * @mbg.generated Tue Mar 12 10:33:24 CST 2019
     */
    public void setMoneyname(String moneyname) {
        this.moneyname = moneyname == null ? null : moneyname.trim();
    }

    @Override
    public String toString() {
        return "MoneyInfo{" +
                "id=" + id +
                ", moneyname='" + moneyname + '\'' +
                ", addTime=" + addTime +
                '}';
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    public Date getAddTime() {

        return addTime;
    }
}