package com.springmvc.pojo;

import org.springframework.stereotype.Repository;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Date;

@Repository
public class Statusputaway {

    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    private String statusname;


    private Date puttime;



    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusputaway.id
     *
     * @param id the value for statusputaway.id
     *
     * @mbg.generated Fri Mar 08 15:40:05 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusputaway.statusName
     *
     * @return the value of statusputaway.statusName
     *
     * @mbg.generated Fri Mar 08 15:40:05 CST 2019
     */
    public String getStatusname() {
        return statusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusputaway.statusName
     *
     * @param statusname the value for statusputaway.statusName
     *
     * @mbg.generated Fri Mar 08 15:40:05 CST 2019
     */
    public void setStatusname(String statusname) {
        this.statusname = statusname == null ? null : statusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusputaway.putTime
     *
     * @return the value of statusputaway.putTime
     *
     * @mbg.generated Fri Mar 08 15:40:05 CST 2019
     */
    public Date getPuttime() {
        return puttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusputaway.putTime
     *
     * @param puttime the value for statusputaway.putTime
     *
     * @mbg.generated Fri Mar 08 15:40:05 CST 2019
     */
    public void setPuttime(Date puttime) {
        this.puttime = puttime;
    }
}